- alias: Turn on light when sun sets
  initial_state: True
  hide_entity: False
  trigger:
    - platform: sun
      event: 'sunset'
      offset: '00:00:00'
    - platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
  condition:
      - condition: time
        before: '22:00:00'
      - condition: sun
        after: sunset
        after_offset: '00:00:00'
      - condition: or
        conditions:
          - condition: state
            entity_id: light.wohnzimmer
            state: 'off'
          - condition: state
            entity_id: light.treppe
            state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.toni
            state: 'home'
          - condition: state
            entity_id: device_tracker.marten
            state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: group.wohnzimmer
      data:
        transition: 3
        brightness: 219
        xy_color: 0.5119, 0.4147
