- alias: hue_sensor_on_treppe
  trigger:
    - platform: mqtt
      topic: hue/motionsensor_3_companion/status
      payload: '1'
  condition:
    - condition: state
      entity_id: sensor.light_sensor_1__darkness
      state: 'true'
    - condition: state
      entity_id: light.treppe
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.treppe
      data:
        transition: 3
        brightness: 3
        xy_color: 0.5612,0.4042
    - service: homeassistant.turn_on
      entity_id: input_boolean.motion_detected_mode

- alias: hue_sensor_off_treppe
  trigger:
    - platform: mqtt
      topic: hue/motionsensor_3_companion/status
      payload: '0'
  condition:
    - condition: state
      entity_id: input_boolean.motion_detected_mode
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.treppe
      data:
        transition: 3
    - service: homeassistant.turn_off
      entity_id: input_boolean.motion_detected_mode