- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - humidity
    - cloudiness
    - dewpointTemperature
- platform: mqtt
  state_topic: 'hue/hue_ambient_light_sensor_1/lightlevel'
  scan_interval: 60
  unit_of_measurement: Lux
  name: 'Living Room Lux'
- platform: mqtt
  state_topic: 'hue/hue_temperature_sensor_1/temperatur'
  value_template: '{{ round(-1) | float / 100 }}'
  scan_interval: 60
  unit_of_measurement: °C
  name: 'Living Room Temperature'
- platform: mqtt
  state_topic: 'hue/hue_ambient_light_sensor_1/dark'
  name: 'light sensor 1 - darkness'