Weather:
  entities:
    - sensor.yr_temperature
    - sensor.yr_symbol
    - sensor.yr_precipitation
    - sensor.yr_windSpeed
    - sensor.yr_humidity
    - sensor.yr_cloudiness
    - sensor.yr_dewpointTemperature