Weather:
  entities:
    - sun.sun
    - sensor.yr_temperature
    - sensor.yr_symbol
    - sensor.yr_precipitation
    - sensor.yr_wind_speed
    - sensor.yr_humidity
    - sensor.yr_cloudiness
    - sensor.yr_dewpoint_temperature